const { test } = require('node:test')

const SingPlurPtbr = require('../')

const singplur = new SingPlurPtbr()

test('plural', (t) => {
  t.assert.strictEqual(singplur.plural('família'), 'famílias')
  t.assert.strictEqual(singplur.plural('utopia'), 'utopias')
  t.assert.strictEqual(singplur.plural('expectativa'), 'expectativas')

  t.assert.strictEqual(singplur.plural('prudente'), 'prudentes')
  t.assert.strictEqual(singplur.plural('incidente'), 'incidentes')
  t.assert.strictEqual(singplur.plural('importante'), 'importantes')

  t.assert.strictEqual(singplur.plural('herói'), 'heróis')
  t.assert.strictEqual(singplur.plural('abacaxi'), 'abacaxis')
  t.assert.strictEqual(singplur.plural('papai'), 'papais')

  t.assert.strictEqual(singplur.plural('significado'), 'significados')
  t.assert.strictEqual(singplur.plural('fato'), 'fatos')
  t.assert.strictEqual(singplur.plural('recesso'), 'recessos')

  t.assert.strictEqual(singplur.plural('museu'), 'museus')
  t.assert.strictEqual(singplur.plural('xampu'), 'xampus')
  t.assert.strictEqual(singplur.plural('caju'), 'cajus')

  t.assert.strictEqual(singplur.plural('alemã'), 'alemãs')
  t.assert.strictEqual(singplur.plural('anã'), 'anãs')
  t.assert.strictEqual(singplur.plural('avelã'), 'avelãs')

  t.assert.strictEqual(singplur.plural('mãe'), 'mães')
  t.assert.strictEqual(singplur.plural('balão'), 'balões')
  t.assert.strictEqual(singplur.plural('questão'), 'questões')

  t.assert.strictEqual(singplur.plural('casa'), 'casas')
  t.assert.strictEqual(singplur.plural('papel'), 'papéis')
  t.assert.strictEqual(singplur.plural('animal'), 'animais')
  t.assert.strictEqual(singplur.plural('flor'), 'flores')
  t.assert.strictEqual(singplur.plural('luz'), 'luzes')
  t.assert.strictEqual(singplur.plural('café'), 'cafés')
  t.assert.strictEqual(singplur.plural('avião'), 'aviões')
  t.assert.strictEqual(singplur.plural('mão'), 'mãos')
  t.assert.strictEqual(singplur.plural('pão'), 'pães')
  t.assert.strictEqual(singplur.plural('homem'), 'homens')
  t.assert.strictEqual(singplur.plural('mulher'), 'mulheres')
  t.assert.strictEqual(singplur.plural('jardim'), 'jardins')
  t.assert.strictEqual(singplur.plural('jovem'), 'jovens')
  t.assert.strictEqual(singplur.plural('país'), 'países')
  t.assert.strictEqual(singplur.plural('mar'), 'mares')
  t.assert.strictEqual(singplur.plural('leão'), 'leões')
  t.assert.strictEqual(singplur.plural('tatu'), 'tatus')
  t.assert.strictEqual(singplur.plural('cor'), 'cores')
  t.assert.strictEqual(singplur.plural('azul'), 'azuis')
  t.assert.strictEqual(singplur.plural('fuzil'), 'fuzis')
  t.assert.strictEqual(singplur.plural('real'), 'reais')
  t.assert.strictEqual(singplur.plural('cidadão'), 'cidadãos')
  t.assert.strictEqual(singplur.plural('móvel'), 'móveis')
  t.assert.strictEqual(singplur.plural('japonês'), 'japoneses')
  t.assert.strictEqual(singplur.plural('inglês'), 'ingleses')
  t.assert.strictEqual(singplur.plural('alemão'), 'alemães')
  t.assert.strictEqual(singplur.plural('irmão'), 'irmãos')
  t.assert.strictEqual(singplur.plural('coração'), 'corações')
  t.assert.strictEqual(singplur.plural('cristão'), 'cristãos')
  t.assert.strictEqual(singplur.plural('pagão'), 'pagãos')
  t.assert.strictEqual(singplur.plural('vulcão'), 'vulcões')
  t.assert.strictEqual(singplur.plural('jornal'), 'jornais')
  t.assert.strictEqual(singplur.plural('papagaio'), 'papagaios')
  t.assert.strictEqual(singplur.plural('hotel'), 'hotéis')
  t.assert.strictEqual(singplur.plural('lençol'), 'lençóis')
  t.assert.strictEqual(singplur.plural('funil'), 'funis')
  t.assert.strictEqual(singplur.plural('pires'), 'pires')
  t.assert.strictEqual(singplur.plural('lápis'), 'lápis')
  t.assert.strictEqual(singplur.plural('tórax'), 'tórax')
  t.assert.strictEqual(singplur.plural('caráter'), 'caracteres')
  t.assert.strictEqual(singplur.plural('fóssil'), 'fósseis')
  t.assert.strictEqual(singplur.plural('fácil'), 'fáceis')
  t.assert.strictEqual(singplur.plural('difícil'), 'difíceis')
  t.assert.strictEqual(singplur.plural('cão'), 'cães')
  t.assert.strictEqual(singplur.plural('pão-duro'), 'pães-duros')
  t.assert.strictEqual(singplur.plural('bem'), 'bens')
  t.assert.strictEqual(singplur.plural('mal'), 'males')
  t.assert.strictEqual(singplur.plural('qualquer'), 'quaisquer')
  t.assert.strictEqual(singplur.plural('questão'), 'questões')

  t.assert.strictEqual(singplur.plural('mal'), 'males')
  t.assert.strictEqual(singplur.plural('cônsul'), 'cônsules')
  t.assert.strictEqual(singplur.plural('mel'), 'méis')
  t.assert.strictEqual(singplur.plural('fel'), 'féis')
  t.assert.strictEqual(singplur.plural('cal'), 'cais')
  t.assert.strictEqual(singplur.plural('caráter'), 'caracteres')
  t.assert.strictEqual(singplur.plural('móvel'), 'móveis')
  t.assert.strictEqual(singplur.plural('hotel'), 'hotéis')
  t.assert.strictEqual(singplur.plural('mão'), 'mãos')
  t.assert.strictEqual(singplur.plural('pão'), 'pães')
  t.assert.strictEqual(singplur.plural('cidadão'), 'cidadãos')
  t.assert.strictEqual(singplur.plural('irmão'), 'irmãos')
  t.assert.strictEqual(singplur.plural('alemão'), 'alemães')
  t.assert.strictEqual(singplur.plural('cristão'), 'cristãos')
  t.assert.strictEqual(singplur.plural('pagão'), 'pagãos')
  t.assert.strictEqual(singplur.plural('acórdão'), 'acórdãos')
  t.assert.strictEqual(singplur.plural('órgão'), 'órgãos')
  t.assert.strictEqual(singplur.plural('sótão'), 'sótãos')
  t.assert.strictEqual(singplur.plural('cão'), 'cães')
  t.assert.strictEqual(singplur.plural('capitão'), 'capitães')
  t.assert.strictEqual(singplur.plural('qualquer'), 'quaisquer')
  t.assert.strictEqual(singplur.plural('azul'), 'azuis')
  t.assert.strictEqual(singplur.plural('feroz'), 'ferozes')
  t.assert.strictEqual(singplur.plural('cível'), 'cíveis')
  t.assert.strictEqual(singplur.plural('juiz'), 'juízes')
  t.assert.strictEqual(singplur.plural('raiz'), 'raízes')
  t.assert.strictEqual(singplur.plural('lei'), 'leis')
  t.assert.strictEqual(singplur.plural('rei'), 'reis')

  t.assert.strictEqual(singplur.plural('dano moral'), 'danos morais')
  t.assert.strictEqual(singplur.plural('juizado especial'), 'juizados especiais')
  t.assert.strictEqual(singplur.plural('dado processual'), 'dados processuais')
  t.assert.strictEqual(singplur.plural('vara cível'), 'varas cíveis')
  t.assert.strictEqual(singplur.plural('questão'), 'questões')
  t.assert.strictEqual(singplur.plural('ação'), 'ações')
  t.assert.strictEqual(singplur.plural('decisão'), 'decisões')
  t.assert.strictEqual(singplur.plural('sentença'), 'sentenças')
  t.assert.strictEqual(singplur.plural('acórdão'), 'acórdãos')
  t.assert.strictEqual(singplur.plural('processo'), 'processos')
  t.assert.strictEqual(singplur.plural('recurso'), 'recursos')
  t.assert.strictEqual(singplur.plural('tribunal'), 'tribunais')
  t.assert.strictEqual(singplur.plural('comarca'), 'comarcas')
  t.assert.strictEqual(singplur.plural('vara'), 'varas')
  t.assert.strictEqual(singplur.plural('juiz'), 'juízes')
  t.assert.strictEqual(singplur.plural('desembargador'), 'desembargadores')
  t.assert.strictEqual(singplur.plural('ministro'), 'ministros')
  t.assert.strictEqual(singplur.plural('advogado'), 'advogados')
  t.assert.strictEqual(singplur.plural('defensor'), 'defensores')
  t.assert.strictEqual(singplur.plural('promotor'), 'promotores')
  t.assert.strictEqual(singplur.plural('procurador'), 'procuradores')
  t.assert.strictEqual(singplur.plural('parte'), 'partes')
  t.assert.strictEqual(singplur.plural('autor'), 'autores')
  t.assert.strictEqual(singplur.plural('réu'), 'réus')
  t.assert.strictEqual(singplur.plural('apelante'), 'apelantes')
  t.assert.strictEqual(singplur.plural('apelado'), 'apelados')
  t.assert.strictEqual(singplur.plural('embargo'), 'embargos')
  t.assert.strictEqual(singplur.plural('agravo'), 'agravos')
  t.assert.strictEqual(singplur.plural('liminar'), 'liminares')
  t.assert.strictEqual(singplur.plural('mandado'), 'mandados')
  t.assert.strictEqual(singplur.plural('injunção'), 'injunções')
  t.assert.strictEqual(singplur.plural('execução'), 'execuções')
  t.assert.strictEqual(singplur.plural('petição'), 'petições')
  t.assert.strictEqual(singplur.plural('requerimento'), 'requerimentos')
  t.assert.strictEqual(singplur.plural('intimação'), 'intimações')
  t.assert.strictEqual(singplur.plural('citação'), 'citações')
  t.assert.strictEqual(singplur.plural('notificação'), 'notificações')
  t.assert.strictEqual(singplur.plural('condenação'), 'condenações')
  t.assert.strictEqual(singplur.plural('absolvição'), 'absolvições')
  t.assert.strictEqual(singplur.plural('nulidade'), 'nulidades')
  t.assert.strictEqual(singplur.plural('preliminar'), 'preliminares')
  t.assert.strictEqual(singplur.plural('custodiado'), 'custodiados')
  t.assert.strictEqual(singplur.plural('detento'), 'detentos')
  t.assert.strictEqual(singplur.plural('penitenciária'), 'penitenciárias')
  t.assert.strictEqual(singplur.plural('prisão'), 'prisões')
  t.assert.strictEqual(singplur.plural('inquérito'), 'inquéritos')
  t.assert.strictEqual(singplur.plural('indiciado'), 'indiciados')
  t.assert.strictEqual(singplur.plural('acusação'), 'acusações')
  t.assert.strictEqual(singplur.plural('denúncia'), 'denúncias')
  t.assert.strictEqual(singplur.plural('testemunha'), 'testemunhas')
  t.assert.strictEqual(singplur.plural('perícia'), 'perícias')
  t.assert.strictEqual(singplur.plural('laudo'), 'laudos')
  t.assert.strictEqual(singplur.plural('contrato'), 'contratos')
  t.assert.strictEqual(singplur.plural('cláusula'), 'cláusulas')
  t.assert.strictEqual(singplur.plural('obrigação'), 'obrigações')
  t.assert.strictEqual(singplur.plural('direito'), 'direitos')
  t.assert.strictEqual(singplur.plural('bem'), 'bens')
  t.assert.strictEqual(singplur.plural('patrimônio'), 'patrimônios')
  t.assert.strictEqual(singplur.plural('responsabilidade'), 'responsabilidades')
  t.assert.strictEqual(singplur.plural('norma'), 'normas')
  t.assert.strictEqual(singplur.plural('lei'), 'leis')
  t.assert.strictEqual(singplur.plural('código'), 'códigos')
  t.assert.strictEqual(singplur.plural('estatuto'), 'estatutos')
  t.assert.strictEqual(singplur.plural('regimento'), 'regimentos')
  t.assert.strictEqual(singplur.plural('constituição'), 'constituições')
  t.assert.strictEqual(singplur.plural('decreto'), 'decretos')
  t.assert.strictEqual(singplur.plural('portaria'), 'portarias')
  t.assert.strictEqual(singplur.plural('resolução'), 'resoluções')
  t.assert.strictEqual(singplur.plural('alínea'), 'alíneas')
  t.assert.strictEqual(singplur.plural('parágrafo'), 'parágrafos')
  t.assert.strictEqual(singplur.plural('inciso'), 'incisos')
  t.assert.strictEqual(singplur.plural('artigo'), 'artigos')
  t.assert.strictEqual(singplur.plural('capítulo'), 'capítulos')
  t.assert.strictEqual(singplur.plural('título'), 'títulos')
  t.assert.strictEqual(singplur.plural('sessão'), 'sessões')
  t.assert.strictEqual(singplur.plural('órgão'), 'órgãos')
  t.assert.strictEqual(singplur.plural('câmara'), 'câmaras')
  t.assert.strictEqual(singplur.plural('turma'), 'turmas')
  t.assert.strictEqual(singplur.plural('plenário'), 'plenários')
  t.assert.strictEqual(singplur.plural('precedente'), 'precedentes')
  t.assert.strictEqual(singplur.plural('jurisprudência'), 'jurisprudências')
  t.assert.strictEqual(singplur.plural('entendimento'), 'entendimentos')
  t.assert.strictEqual(singplur.plural('doutrina'), 'doutrinas')
  t.assert.strictEqual(singplur.plural('parecer'), 'pareceres')
  t.assert.strictEqual(singplur.plural('ofício'), 'ofícios')
  t.assert.strictEqual(singplur.plural('certidão'), 'certidões')
  t.assert.strictEqual(singplur.plural('intimado'), 'intimados')
  t.assert.strictEqual(singplur.plural('contribuinte'), 'contribuintes')
  t.assert.strictEqual(singplur.plural('servidor'), 'servidores')
  t.assert.strictEqual(singplur.plural('perito'), 'peritos')
  t.assert.strictEqual(singplur.plural('auxiliar'), 'auxiliares')
  t.assert.strictEqual(singplur.plural('estagiário'), 'estagiários')
  t.assert.strictEqual(singplur.plural('consulta'), 'consultas')
  t.assert.strictEqual(singplur.plural('litígio'), 'litígios')
  t.assert.strictEqual(singplur.plural('conflito'), 'conflitos')
  t.assert.strictEqual(singplur.plural('acordo'), 'acordos')
  t.assert.strictEqual(singplur.plural('transação'), 'transações')
  t.assert.strictEqual(singplur.plural('conciliação'), 'conciliações')
  t.assert.strictEqual(singplur.plural('mediação'), 'mediações')
  t.assert.strictEqual(singplur.plural('arbitragem'), 'arbitragens')
  t.assert.strictEqual(singplur.plural('custa'), 'custas')
  t.assert.strictEqual(singplur.plural('honorário'), 'honorários')
  t.assert.strictEqual(singplur.plural('auto'), 'autos')
})

test('singular', (t) => {
  t.assert.strictEqual(singplur.singular('casas'), 'casa')
  t.assert.strictEqual(singplur.singular('animais'), 'animal')
  t.assert.strictEqual(singplur.singular('papéis'), 'papel')
  t.assert.strictEqual(singplur.singular('males'), 'mal')
  t.assert.strictEqual(singplur.singular('balões'), 'balão')
  t.assert.strictEqual(singplur.singular('casas bonitas'), 'casa bonita')

  t.assert.strictEqual(singplur.singular('casas'), 'casa')
  t.assert.strictEqual(singplur.singular('papéis'), 'papel')
  t.assert.strictEqual(singplur.singular('animais'), 'animal')
  t.assert.strictEqual(singplur.singular('flores'), 'flor')
  t.assert.strictEqual(singplur.singular('luzes'), 'luz')
  t.assert.strictEqual(singplur.singular('cafés'), 'café')
  t.assert.strictEqual(singplur.singular('aviões'), 'avião')
  t.assert.strictEqual(singplur.singular('mãos'), 'mão')
  t.assert.strictEqual(singplur.singular('pães'), 'pão')
  t.assert.strictEqual(singplur.singular('homens'), 'homem')
  t.assert.strictEqual(singplur.singular('mulheres'), 'mulher')
  t.assert.strictEqual(singplur.singular('jardins'), 'jardim')
  t.assert.strictEqual(singplur.singular('jovens'), 'jovem')
  t.assert.strictEqual(singplur.singular('países'), 'país')
  t.assert.strictEqual(singplur.singular('mares'), 'mar')
  t.assert.strictEqual(singplur.singular('leões'), 'leão')
  t.assert.strictEqual(singplur.singular('tatus'), 'tatu')
  t.assert.strictEqual(singplur.singular('cores'), 'cor')
  t.assert.strictEqual(singplur.singular('azuis'), 'azul')
  t.assert.strictEqual(singplur.singular('fuzis'), 'fuzil')
  t.assert.strictEqual(singplur.singular('reais'), 'real')
  t.assert.strictEqual(singplur.singular('cidadãos'), 'cidadão')
  t.assert.strictEqual(singplur.singular('móveis'), 'móvel')
  t.assert.strictEqual(singplur.singular('japoneses'), 'japonês')
  t.assert.strictEqual(singplur.singular('alemães'), 'alemão')
  t.assert.strictEqual(singplur.singular('irmãos'), 'irmão')
  t.assert.strictEqual(singplur.singular('jornais'), 'jornal')
  t.assert.strictEqual(singplur.singular('papagaios'), 'papagaio')
  t.assert.strictEqual(singplur.singular('hotéis'), 'hotel')
  t.assert.strictEqual(singplur.singular('lençóis'), 'lençol')
  t.assert.strictEqual(singplur.singular('funis'), 'funil')
  t.assert.strictEqual(singplur.singular('capitães'), 'capitão')
  t.assert.strictEqual(singplur.singular('pires'), 'pires')
  t.assert.strictEqual(singplur.singular('lápis'), 'lápis')
  t.assert.strictEqual(singplur.singular('tórax'), 'tórax')
  t.assert.strictEqual(singplur.singular('caracteres'), 'caráter')
  t.assert.strictEqual(singplur.singular('fósseis'), 'fóssil')
  t.assert.strictEqual(singplur.singular('fáceis'), 'fácil')
  t.assert.strictEqual(singplur.singular('cães'), 'cão')

  t.assert.strictEqual(singplur.singular('danos morais'), 'dano moral')
  t.assert.strictEqual(singplur.singular('juizados especiais'), 'juizado especial')
  t.assert.strictEqual(singplur.singular('dados processuais'), 'dado processual')
  t.assert.strictEqual(singplur.singular('varas cíveis'), 'vara cível')
  t.assert.strictEqual(singplur.singular('processos'), 'processo')
  t.assert.strictEqual(singplur.singular('recursos'), 'recurso')
  t.assert.strictEqual(singplur.singular('ações'), 'ação')
  t.assert.strictEqual(singplur.singular('decisões'), 'decisão')
  t.assert.strictEqual(singplur.singular('sentenças'), 'sentença')
  t.assert.strictEqual(singplur.singular('acórdãos'), 'acórdão')
  t.assert.strictEqual(singplur.singular('tribunais'), 'tribunal')
  t.assert.strictEqual(singplur.singular('comarcas'), 'comarca')
  t.assert.strictEqual(singplur.singular('varas'), 'vara')
  t.assert.strictEqual(singplur.singular('juízes'), 'juiz')
  t.assert.strictEqual(singplur.singular('desembargadores'), 'desembargador')
  t.assert.strictEqual(singplur.singular('ministros'), 'ministro')
  t.assert.strictEqual(singplur.singular('advogados'), 'advogado')
  t.assert.strictEqual(singplur.singular('defensores'), 'defensor')
  t.assert.strictEqual(singplur.singular('promotores'), 'promotor')
  t.assert.strictEqual(singplur.singular('procuradores'), 'procurador')
  t.assert.strictEqual(singplur.singular('partes'), 'parte')
  t.assert.strictEqual(singplur.singular('autores'), 'autor')
  t.assert.strictEqual(singplur.singular('réus'), 'réu')
  t.assert.strictEqual(singplur.singular('apelantes'), 'apelante')
  t.assert.strictEqual(singplur.singular('apelados'), 'apelado')
  t.assert.strictEqual(singplur.singular('embargos'), 'embargo')
  t.assert.strictEqual(singplur.singular('agravos'), 'agravo')
  t.assert.strictEqual(singplur.singular('liminares'), 'liminar')
  t.assert.strictEqual(singplur.singular('mandados'), 'mandado')
  t.assert.strictEqual(singplur.singular('injunções'), 'injunção')
  t.assert.strictEqual(singplur.singular('execuções'), 'execução')
  t.assert.strictEqual(singplur.singular('petições'), 'petição')
  t.assert.strictEqual(singplur.singular('requerimentos'), 'requerimento')
  t.assert.strictEqual(singplur.singular('intimações'), 'intimação')
  t.assert.strictEqual(singplur.singular('citações'), 'citação')
  t.assert.strictEqual(singplur.singular('notificações'), 'notificação')
  t.assert.strictEqual(singplur.singular('condenações'), 'condenação')
  t.assert.strictEqual(singplur.singular('absolvições'), 'absolvição')
  t.assert.strictEqual(singplur.singular('nulidades'), 'nulidade')
  t.assert.strictEqual(singplur.singular('preliminares'), 'preliminar')
  t.assert.strictEqual(singplur.singular('custodiados'), 'custodiado')
  t.assert.strictEqual(singplur.singular('detentos'), 'detento')
  t.assert.strictEqual(singplur.singular('penitenciárias'), 'penitenciária')
  t.assert.strictEqual(singplur.singular('prisões'), 'prisão')
  t.assert.strictEqual(singplur.singular('inquéritos'), 'inquérito')
  t.assert.strictEqual(singplur.singular('indiciados'), 'indiciado')
  t.assert.strictEqual(singplur.singular('acusações'), 'acusação')
  t.assert.strictEqual(singplur.singular('denúncias'), 'denúncia')
  t.assert.strictEqual(singplur.singular('testemunhas'), 'testemunha')
  t.assert.strictEqual(singplur.singular('perícias'), 'perícia')
  t.assert.strictEqual(singplur.singular('laudos'), 'laudo')
  t.assert.strictEqual(singplur.singular('contratos'), 'contrato')
  t.assert.strictEqual(singplur.singular('cláusulas'), 'cláusula')
  t.assert.strictEqual(singplur.singular('obrigações'), 'obrigação')
  t.assert.strictEqual(singplur.singular('direitos'), 'direito')
  t.assert.strictEqual(singplur.singular('bens'), 'bem')
  t.assert.strictEqual(singplur.singular('patrimônios'), 'patrimônio')
  t.assert.strictEqual(singplur.singular('responsabilidades'), 'responsabilidade')
  t.assert.strictEqual(singplur.singular('normas'), 'norma')
  t.assert.strictEqual(singplur.singular('leis'), 'lei')
  t.assert.strictEqual(singplur.singular('códigos'), 'código')
  t.assert.strictEqual(singplur.singular('estatutos'), 'estatuto')
  t.assert.strictEqual(singplur.singular('regimentos'), 'regimento')
  t.assert.strictEqual(singplur.singular('constituições'), 'constituição')
  t.assert.strictEqual(singplur.singular('decretos'), 'decreto')
  t.assert.strictEqual(singplur.singular('portarias'), 'portaria')
  t.assert.strictEqual(singplur.singular('resoluções'), 'resolução')
  t.assert.strictEqual(singplur.singular('alíneas'), 'alínea')
  t.assert.strictEqual(singplur.singular('parágrafos'), 'parágrafo')
  t.assert.strictEqual(singplur.singular('incisos'), 'inciso')
  t.assert.strictEqual(singplur.singular('artigos'), 'artigo')
  t.assert.strictEqual(singplur.singular('capítulos'), 'capítulo')
  t.assert.strictEqual(singplur.singular('títulos'), 'título')
  t.assert.strictEqual(singplur.singular('sessões'), 'sessão')
  t.assert.strictEqual(singplur.singular('órgãos'), 'órgão')
  t.assert.strictEqual(singplur.singular('câmaras'), 'câmara')
  t.assert.strictEqual(singplur.singular('turmas'), 'turma')
  t.assert.strictEqual(singplur.singular('plenos'), 'pleno')
  t.assert.strictEqual(singplur.singular('precedentes'), 'precedente')
  t.assert.strictEqual(singplur.singular('jurisprudências'), 'jurisprudência')
  t.assert.strictEqual(singplur.singular('entendimentos'), 'entendimento')
  t.assert.strictEqual(singplur.singular('doutrinas'), 'doutrina')
  t.assert.strictEqual(singplur.singular('pareceres'), 'parecer')
  t.assert.strictEqual(singplur.singular('ofícios'), 'ofício')
  t.assert.strictEqual(singplur.singular('certidões'), 'certidão')
  t.assert.strictEqual(singplur.singular('intimados'), 'intimado')
  t.assert.strictEqual(singplur.singular('contribuintes'), 'contribuinte')
  t.assert.strictEqual(singplur.singular('servidores'), 'servidor')
  t.assert.strictEqual(singplur.singular('peritos'), 'perito')
  t.assert.strictEqual(singplur.singular('auxiliares'), 'auxiliar')
  t.assert.strictEqual(singplur.singular('estagiários'), 'estagiário')
  t.assert.strictEqual(singplur.singular('consultas'), 'consulta')
  t.assert.strictEqual(singplur.singular('litígios'), 'litígio')
  t.assert.strictEqual(singplur.singular('conflitos'), 'conflito')
  t.assert.strictEqual(singplur.singular('acordos'), 'acordo')
  t.assert.strictEqual(singplur.singular('transações'), 'transação')
  t.assert.strictEqual(singplur.singular('conciliações'), 'conciliação')
  t.assert.strictEqual(singplur.singular('mediações'), 'mediação')
  t.assert.strictEqual(singplur.singular('arbitragens'), 'arbitragem')
  t.assert.strictEqual(singplur.singular('custas'), 'custa')
  t.assert.strictEqual(singplur.singular('honorários'), 'honorário')
  t.assert.strictEqual(singplur.singular('autos'), 'auto')
})

test('validação de entrada', (t) => {
  t.assert.strictEqual(singplur.plural(''), '')
  t.assert.strictEqual(singplur.singular(''), '')
  t.assert.strictEqual(singplur.plural('  casa  '), 'casas')
  t.assert.strictEqual(singplur.singular('  casas  '), 'casa')

  t.assert.throws(() => singplur.plural(null), TypeError)
  t.assert.throws(() => singplur.plural(undefined), TypeError)
  t.assert.throws(() => singplur.singular(null), TypeError)
  t.assert.throws(() => singplur.singular(undefined), TypeError)

  t.assert.throws(() => singplur.plural(123), TypeError)
  t.assert.throws(() => singplur.plural({}), TypeError)
  t.assert.throws(() => singplur.plural([]), TypeError)
  t.assert.throws(() => singplur.singular(123), TypeError)
})

test('capitalização', (t) => {
  t.assert.strictEqual(singplur.plural('Casa'), 'Casas')
  t.assert.strictEqual(singplur.singular('Casas'), 'Casa')

  t.assert.strictEqual(singplur.plural('CASA'), 'CASAS')
  t.assert.strictEqual(singplur.singular('CASAS'), 'CASA')

  t.assert.strictEqual(singplur.plural('Mão'), 'Mãos')
  t.assert.strictEqual(singplur.singular('Mãos'), 'Mão')
  t.assert.strictEqual(singplur.plural('CÃO'), 'CÃES')
  t.assert.strictEqual(singplur.singular('CÃES'), 'CÃO')
})

test('múltiplas palavras', (t) => {
  t.assert.strictEqual(singplur.plural('casa bonita'), 'casas bonitas')
  t.assert.strictEqual(singplur.singular('casas bonitas'), 'casa bonita')

  t.assert.strictEqual(singplur.plural('papel azul'), 'papéis azuis')
  t.assert.strictEqual(singplur.singular('papéis azuis'), 'papel azul')

  t.assert.strictEqual(singplur.plural('animal feroz'), 'animais ferozes')
  t.assert.strictEqual(singplur.singular('animais ferozes'), 'animal feroz')
})

test('palavras invariáveis e sem plural', (t) => {
  t.assert.strictEqual(singplur.plural('pires'), 'pires')
  t.assert.strictEqual(singplur.singular('pires'), 'pires')
  t.assert.strictEqual(singplur.plural('lápis'), 'lápis')
  t.assert.strictEqual(singplur.singular('lápis'), 'lápis')

  t.assert.strictEqual(singplur.plural('Pires'), 'Pires')
  t.assert.strictEqual(singplur.plural('LÁPIS'), 'LÁPIS')
})

test('invariaveis', (t) => {
  const invariaveis = new SingPlurPtbr({
    invariaveis: ['habeas-corpus', 'habeas-data'],
    singularPlural: {
      sacristão: 'sacristães'
    }
  })

  t.assert.strictEqual(invariaveis.singular('habeas-corpus'), 'habeas-corpus')
  t.assert.strictEqual(invariaveis.plural('habeas-corpus'), 'habeas-corpus')

  t.assert.strictEqual(invariaveis.singular('habeas-data'), 'habeas-data')
  t.assert.strictEqual(invariaveis.plural('habeas-data'), 'habeas-data')

  t.assert.strictEqual(invariaveis.plural('sacristão'), 'sacristães')
})

test('palavras no plural', (t) => {
  t.assert.strictEqual(singplur.isPlural('casas'), true)
  t.assert.strictEqual(singplur.isPlural('animais'), true)
  t.assert.strictEqual(singplur.isPlural('papéis'), true)
  t.assert.strictEqual(singplur.isPlural('flores'), true)
  t.assert.strictEqual(singplur.isPlural('luzes'), true)
  t.assert.strictEqual(singplur.isPlural('aviões'), true)
  t.assert.strictEqual(singplur.isPlural('mãos'), true)
  t.assert.strictEqual(singplur.isPlural('pães'), true)
  t.assert.strictEqual(singplur.isPlural('homens'), true)
  t.assert.strictEqual(singplur.isPlural('jardins'), true)

  t.assert.strictEqual(singplur.isPlural('males'), true)
  t.assert.strictEqual(singplur.isPlural('cônsules'), true)
  t.assert.strictEqual(singplur.isPlural('caracteres'), true)
  t.assert.strictEqual(singplur.isPlural('móveis'), true)

  t.assert.strictEqual(singplur.isPlural('guarda-chuvas'), true)
  t.assert.strictEqual(singplur.isPlural('obras-primas'), true)
})

test('palavras no singular', (t) => {
  t.assert.strictEqual(singplur.isPlural('casa'), false)
  t.assert.strictEqual(singplur.isPlural('animal'), false)
  t.assert.strictEqual(singplur.isPlural('papel'), false)
  t.assert.strictEqual(singplur.isPlural('flor'), false)
  t.assert.strictEqual(singplur.isPlural('luz'), false)
  t.assert.strictEqual(singplur.isPlural('avião'), false)
  t.assert.strictEqual(singplur.isPlural('mão'), false)
  t.assert.strictEqual(singplur.isPlural('pão'), false)
  t.assert.strictEqual(singplur.isPlural('homem'), false)
  t.assert.strictEqual(singplur.isPlural('jardim'), false)

  t.assert.strictEqual(singplur.isPlural('mal'), false)
  t.assert.strictEqual(singplur.isPlural('cônsul'), false)
  t.assert.strictEqual(singplur.isPlural('caráter'), false)
  t.assert.strictEqual(singplur.isPlural('móvel'), false)

  // Palavras compostas no singular
  t.assert.strictEqual(singplur.isPlural('guarda-chuva'), false)
  t.assert.strictEqual(singplur.isPlural('obra-prima'), false)
})

test('palavras invariáveis', (t) => {
  // Palavras invariáveis sempre retornam false
  t.assert.strictEqual(singplur.isPlural('pires'), false)
  t.assert.strictEqual(singplur.isPlural('lápis'), false)
  t.assert.strictEqual(singplur.isPlural('tórax'), false)
  t.assert.strictEqual(singplur.isPlural('status'), false)
  t.assert.strictEqual(singplur.isPlural('vírus'), false)
  t.assert.strictEqual(singplur.isPlural('lapsus'), false)
  t.assert.strictEqual(singplur.isPlural('campus'), false)
})

test('isPlural 1', (t) => {
  t.assert.strictEqual(singplur.isPlural(''), false)

  t.assert.strictEqual(singplur.isPlural('Casas'), true)
  t.assert.strictEqual(singplur.isPlural('Casa'), false)
  t.assert.strictEqual(singplur.isPlural('CASAS'), true)
  t.assert.strictEqual(singplur.isPlural('CASA'), false)

  t.assert.strictEqual(singplur.isPlural('casas bonitas'), true)
  t.assert.strictEqual(singplur.isPlural('casa bonita'), false)

  t.assert.strictEqual(singplur.isPlural('  casas  '), true)
  t.assert.strictEqual(singplur.isPlural('  casa  '), false)

  t.assert.throws(() => singplur.isPlural(null), TypeError)
  t.assert.throws(() => singplur.isPlural(undefined), TypeError)

  t.assert.throws(() => singplur.isPlural(123), TypeError)
  t.assert.throws(() => singplur.isPlural({}), TypeError)
  t.assert.throws(() => singplur.isPlural([]), TypeError)
})

test('isPlural 2', (t) => {
  t.assert.strictEqual(singplur.isPlural('processos'), true)
  t.assert.strictEqual(singplur.isPlural('tribunais'), true)
  t.assert.strictEqual(singplur.isPlural('juízes'), true)
  t.assert.strictEqual(singplur.isPlural('ações'), true)
  t.assert.strictEqual(singplur.isPlural('decisões'), true)
  t.assert.strictEqual(singplur.isPlural('acórdãos'), true)

  t.assert.strictEqual(singplur.isPlural('processo'), false)
  t.assert.strictEqual(singplur.isPlural('tribunal'), false)
  t.assert.strictEqual(singplur.isPlural('juiz'), false)
  t.assert.strictEqual(singplur.isPlural('ação'), false)
  t.assert.strictEqual(singplur.isPlural('decisão'), false)
  t.assert.strictEqual(singplur.isPlural('acórdão'), false)
})
